
# For help with configuration see https://github.com/rszyma/kanata-tray/blob/main/README.md
"$schema" = "https://raw.githubusercontent.com/rszyma/kanata-tray/v0.1.0/doc/config_schema.json"

general.allow_concurrent_presets = false

[defaults]
kanata_executable = '/home/lugo/.local/bin/kanata' # if empty or omitted, system $PATH will be searched.
kanata_config = '/home/lugo/repos/keyboards/kanata/kanata.kbd' # if empty or not omitted, kanata default config locations will be used.
tcp_port = 5829 # if not specified, defaults to 5829

[defaults.hooks]
# Hooks allow running custom commands on specific events (e.g. when starting preset).
# Documentation: https://github.com/rszyma/kanata-tray/blob/main/doc/hooks.md

[defaults.layer_icons]
base = 'base.ico'
numbers = 'numbers.ico'
arrows = 'arrows.ico'
'*' = 'other.ico'

[presets.'Main Preset']
kanata_executable = '/home/lugo/.local/bin/kanata' # if empty or omitted, system $PATH will be searched.
kanata_config = '/home/lugo/repos/keyboards/kanata/kanata.kbd' # if empty or not omitted, kanata default config locations will be used.
autorun = true
